[build]
    publish = "public/"
    command = "./scripts/build-online.sh"

[context.production.environment]
    HUGO_VERSION = "0.33"
    HUGO_ENV = "production"

[context.deploy-preview.environment]
    HUGO_VERSION = "0.33"

[context.branch-deploy.environment]
    HUGO_VERSION = "0.33"
